### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by David-Baddeley** [csoeller/PYME-camprops-mock#1]
Thanks heaps for making a start on this. Opening this as a place to put some comments ...

- I'm not at all keen on having a different format for different cameras, this makes it hard for people to get their heads around on a couple of levels (both having to write the info differently and having to remember what to call the file).
- deciding on the common format was the main thing which was holding up an implementation previously (although this shouldn't be that hard)

I suspect following the Zyla format is likely to make the most sense (noise properties keyed by preamp setting) as I think it covers all use cases. The IXon noise model is a bit broken (we just write the values for one preamp gain setting, under the assumption that that is the setting we use - this is a bit safer now as we actually ask for that setting, but at one point it depended on what was last used in the Andor software) and this would be a good chance to fix it. The Ixon is a bit complex in that it has a choice of 2 amplifiers (EMCCD and conventional) which have 3 and 2 different preamp gain settings respectively for a total of 5 possible noise configurations. It should be possible to hash these into one key, however.

I think the following makes sense as a specification.

- Cameras implement a function or property (let's call it `_preamp_noise_key()` for this discussion, but it should only ever get called from within their `.noiseProperties` property so could also be inline within that function). The simplest implementation just returns `default`
- we implement a `get_noise_properties(serial_num, preamp_noise_key='default')` function in the camera base class (or alternatively a `get_camera_noise_properties(serial_num, preamp_noise_key='default')` function in `PYME.config` - if we are traversing the config directories this might make more sense)
- this looks for `camera_noise_props.yaml` or similar in each of the config directories, and reads everything into one dictionary (potentially on either import or first access, caching the resulting dictionary)

We could then simplify the .yaml format quite a bit:

- it shouldn't be necessary to nest `noiseProperties` within `properties`
- I don't see a strong argument for having separate keys for `name` and `model`

Something like this ...

``` yaml
VSC-00954:
  model: Andor Zyla 4.2
  noise_properties:
    12-bit (high well capacity):
        ADOffset: 100
        ElectronsPerCount: 6.97
        ReadNoise: 5.96
        SaturationThreshold: 2047
    12-bit (low noise):
        ADOffset: 100
        ElectronsPerCount: 0.28
        ReadNoise: 1.1
        SaturationThreshold: 2047
    16-bit (low noise & high well capacity):
        ADOffset: 100
        ElectronsPerCount: 0.5
        ReadNoise: 1.33
        SaturationThreshold: 65535

5414:
  model: Andor IXON
  noise_properties:
    EM amplifier preamp 0:
      ADOffset: 413
      DefaultEMGain: 90
      ElectronsPerCount: 25.24
      NGainStages: 536
      ReadNoise: 61.33
      SaturationThreshold: 16383

100233 : 
  model: Hamamatsu ORCA Flash 4.2
  noise_properties:
    default:
        ReadNoise: 1.65
        ElectronsPerCount: 0.47
        NGainStages: 0
        ADOffset: 100
        DefaultEMGain: 1
        SaturationThreshold: 65535
```

Suspect we could come up with a better preamp hash for the Ixon, but this should be a good start.
